### ISSUE TITLE
A plan (for tutorials)

### ISSUE THREAD

**Issue by privacywarrior** [theprivacyguide/theprivacyguide.org#10]
Can we have a plan of tutorials to be made?
Maybe also ordered by priority.

**Comment by ghost** [comment]
There is an issue for each one. https://github.com/theprivacyguide/theprivacyguide.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22Add+Tutorial%22 Good idea to order them by priority, I'll add priority labels. Also, I consider creating a development branch.

**Comment by ghost** [comment]
https://github.com/theprivacyguide/theprivacyguide.org/projects/2
